In [1]:
import pandas as pd
import seaborn as sns 
import numpy as np
import datetime

In [3]:
df = pd.read_csv("./data/Google_Stock_Price.csv")
df

       timestamp    open    high     low    close    volume
0     2004-08-19  100.01  104.06   95.96  100.335  44659000
1     2004-08-20  101.01  109.08  100.50  108.310  22834300
2     2004-08-23  110.76  113.48  109.05  109.400  18256100
3     2004-08-24  111.24  111.60  103.57  104.870  15247300
4     2004-08-25  104.76  108.00  103.88  106.000   9188600
...          ...     ...     ...     ...      ...       ...
4996  2024-06-26  182.63  184.51  182.48  183.880  19838972
4997  2024-06-27  184.18  186.05  184.02  185.410  18848884
4998  2024-06-28  184.32  185.13  181.96  182.150  29156644
4999  2024-07-01  183.03  183.88  181.30  182.990  16006128
5000  2024-07-02  182.05  185.57  181.56  185.240  17372485

[5001 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  5001 non-null   object
 1   open       5001 non-null   float64
 2   high       5001 non-null   float64
 3   low        5001 non-null   float64
 4   close      5001 non-null   float64
 5   volume     5001 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 234.6+ KB

In [5]:
df.describe()

              open         high          low        close        volume
count  5001.000000  5001.000000  5001.000000  5001.000000  5.001000e+03
mean    791.497280   799.376622   783.214127   791.441941  8.797586e+06
std     613.276474   619.413907   606.722461   613.194639  1.104632e+07
min      85.400000    86.520000    83.340000    83.430000  3.845900e+04
25%     438.430000   445.000000   431.670000   437.920000  1.769069e+06
50%     596.140000   599.980000   591.670000   595.730000  4.229700e+06
75%    1032.040000  1043.980000  1020.450000  1032.640000  1.133440e+07
max    3025.000000  3030.931500  2977.980000  2996.770000  1.194550e+08

In [6]:
df.isnull().sum()

timestamp    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64

In [7]:
df.duplicated().sum()

0