In [30]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/pthiagu2/DataMining/master/WA_Fn-UseC_-Accounts-Receivable.csv')

In [31]:
df

,countryCode,customerID,PaperlessDate,invoiceNumber,InvoiceDate,DueDate,InvoiceAmount,Disputed,SettledDate,PaperlessBill,DaysToSettle,DaysLate
0,391,0379-NEVHP,4/6/2013,611365,1/2/2013,2/1/2013,55.94,No,1/15/2013,Paper,13,0
1,406,8976-AMJEO,3/3/2012,7900770,1/26/2013,2/25/2013,61.74,Yes,3/3/2013,Electronic,36,6
2,391,2820-XGXSB,1/26/2012,9231909,7/3/2013,8/2/2013,65.88,No,7/8/2013,Electronic,5,0
3,406,9322-YCTQO,4/6/2012,9888306,2/10/2013,3/12/2013,105.92,No,3/17/2013,Electronic,35,5
4,818,6627-ELFBK,11/26/2012,15752855,10/25/2012,11/24/2012,72.27,Yes,11/28/2012,Paper,34,4
...,...,...,...,...,...,...,...,...,...,...,...,...
2461,391,6708-DPYTF,8/2/2012,9982796720,10/18/2013,11/17/2013,79.61,No,12/1/2013,Electronic,44,14
2462,391,9841-XLGBV,1/3/2013,9983237240,9/19/2012,10/19/2012,38.25,No,10/13/2012,Paper,24,0
2463,770,7856-ODQFO,8/5/2012,9986249860,7/2/2012,8/1/2012,67.59,No,7/27/2012,Paper,25,0
2464,770,7050-KQLDO,9/29/2012,9989225541,4/27/2012,5/27/2012,53.16,No,5/18/2012,Paper,21,0
2465,406,9758-AIEIK,4/23/2012,9990243864,7/4/2013,8/3/2013,68.66,No,7/18/2013,Electronic,14,0

In [32]:

df.drop(['PaperlessDate','invoiceNumber', 'DueDate', 'Disputed', 'SettledDate','PaperlessBill','DaysToSettle'], axis = 1,inplace = True)
df

      countryCode  customerID InvoiceDate  InvoiceAmount  DaysLate
0             391  0379-NEVHP    1/2/2013          55.94         0
1             406  8976-AMJEO   1/26/2013          61.74         6
2             391  2820-XGXSB    7/3/2013          65.88         0
3             406  9322-YCTQO   2/10/2013         105.92         5
4             818  6627-ELFBK  10/25/2012          72.27         4
...           ...         ...         ...            ...       ...
2461          391  6708-DPYTF  10/18/2013          79.61        14
2462          391  9841-XLGBV   9/19/2012          38.25         0
2463          770  7856-ODQFO    7/2/2012          67.59         0
2464          770  7050-KQLDO   4/27/2012          53.16         0
2465          406  9758-AIEIK    7/4/2013          68.66         0

[2466 rows x 5 columns]

In [33]:
df.groupby('customerID')['DaysLate'].mean().describe()

count    100.000000
mean       3.513581
std        4.298480
min        0.000000
25%        0.198593
50%        1.684113
75%        5.346154
max       19.600000
Name: DaysLate, dtype: float64

In [34]:
# Make sure data is in the right format
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df

      countryCode  customerID InvoiceDate  InvoiceAmount  DaysLate
0             391  0379-NEVHP  2013-01-02          55.94         0
1             406  8976-AMJEO  2013-01-26          61.74         6
2             391  2820-XGXSB  2013-07-03          65.88         0
3             406  9322-YCTQO  2013-02-10         105.92         5
4             818  6627-ELFBK  2012-10-25          72.27         4
...           ...         ...         ...            ...       ...
2461          391  6708-DPYTF  2013-10-18          79.61        14
2462          391  9841-XLGBV  2012-09-19          38.25         0
2463          770  7856-ODQFO  2012-07-02          67.59         0
2464          770  7050-KQLDO  2012-04-27          53.16         0
2465          406  9758-AIEIK  2013-07-04          68.66         0

[2466 rows x 5 columns]

In [35]:
df = df.sort_values('InvoiceDate')
# Global Days Late Last 30 Days 
df["GlobalDaysLateLast30days"] = df.rolling(window = '30d', on = "InvoiceDate").DaysLate.mean()
df

,countryCode,customerID,InvoiceDate,InvoiceAmount,DaysLate,GlobalDaysLateLast30days
1279,391,6708-DPYTF,2012-01-03,55.37,14,14.000000
75,770,3993-QUNVJ,2012-01-03,50.39,0,7.000000
1584,406,5164-VMYWJ,2012-01-03,71.33,0,4.666667
1460,818,1604-LIFKX,2012-01-03,97.60,23,9.250000
1494,818,8887-NCUZC,2012-01-03,15.99,13,10.000000
...,...,...,...,...,...,...
543,391,7209-MDWKR,2013-12-02,67.69,0,1.859813
2326,897,6391-GBFQJ,2013-12-02,18.05,0,1.842593
2425,897,6391-GBFQJ,2013-12-02,8.38,0,1.825688
599,818,8887-NCUZC,2013-12-02,49.51,6,1.863636
2046,770,9149-MATVB,2013-12-02,38.50,0,1.846847

In [37]:
# Global Days Late Last 3 Invoices (min_periods = 1 to avoid NaN) 
df["GlobalDaysLateLast3Inv"] = df.rolling(window = 3, on = "InvoiceDate").DaysLate.mean()
df.tail()

,countryCode,customerID,InvoiceDate,InvoiceAmount,DaysLate,GlobalDaysLateLast30days,GlobalDaysLateLast3Inv
543,391,7209-MDWKR,2013-12-02,67.69,0,1.859813,1.333333
2326,897,6391-GBFQJ,2013-12-02,18.05,0,1.842593,1.333333
2425,897,6391-GBFQJ,2013-12-02,8.38,0,1.825688,0.000000
599,818,8887-NCUZC,2013-12-02,49.51,6,1.863636,2.000000
2046,770,9149-MATVB,2013-12-02,38.50,0,1.846847,2.000000

In [39]:
# Customer last 3 Invoices average days late
df["AvLateLast3"] = df.groupby("customerID").rolling(window = 3,min_periods = 1).\
                              DaysLate.mean().reset_index().set_index("level_1").\
                              sort_index()["DaysLate"]
df

,countryCode,customerID,InvoiceDate,InvoiceAmount,DaysLate,GlobalDaysLateLast30days,GlobalDaysLateLast3Inv,AvLateLast3
1279,391,6708-DPYTF,2012-01-03,55.37,14,14.000000,NaN,14.000000
75,770,3993-QUNVJ,2012-01-03,50.39,0,7.000000,NaN,0.000000
1584,406,5164-VMYWJ,2012-01-03,71.33,0,4.666667,4.666667,0.000000
1460,818,1604-LIFKX,2012-01-03,97.60,23,9.250000,7.666667,23.000000
1494,818,8887-NCUZC,2012-01-03,15.99,13,10.000000,12.000000,13.000000
...,...,...,...,...,...,...,...,...
543,391,7209-MDWKR,2013-12-02,67.69,0,1.859813,1.333333,0.333333
2326,897,6391-GBFQJ,2013-12-02,18.05,0,1.842593,1.333333,3.666667
2425,897,6391-GBFQJ,2013-12-02,8.38,0,1.825688,0.000000,3.666667
599,818,8887-NCUZC,2013-12-02,49.51,6,1.863636,2.000000,2.333333
2046,770,9149-MATVB,2013-12-02,38.50,0,1.846847,2.000000,0.000000

In [41]:

# Customer Average Days Late Last 30 days   
mean_30d = (
    df
    .set_index('InvoiceDate') # !important
    .sort_index()
    .groupby('customerID')
    .rolling('30d')['DaysLate'].mean()
    .reset_index(name='CustomerDaysLate_30days')
)

# merge the rolling mean back to original dataframe
df = df.merge(mean_30d) 

df

,countryCode,customerID,InvoiceDate,InvoiceAmount,DaysLate,GlobalDaysLateLast30days,GlobalDaysLateLast3Inv,AvLateLast3,CustomerDaysLate_30days
0,391,6708-DPYTF,2012-01-03,55.37,14,14.000000,NaN,14.000000,14.000000
1,770,3993-QUNVJ,2012-01-03,50.39,0,7.000000,NaN,0.000000,0.000000
2,406,5164-VMYWJ,2012-01-03,71.33,0,4.666667,4.666667,0.000000,0.000000
3,818,1604-LIFKX,2012-01-03,97.60,23,9.250000,7.666667,23.000000,23.000000
4,818,8887-NCUZC,2012-01-03,15.99,13,10.000000,12.000000,13.000000,13.000000
...,...,...,...,...,...,...,...,...,...
2709,897,6391-GBFQJ,2013-12-02,8.38,0,1.825688,0.000000,3.666667,5.500000
2710,897,6391-GBFQJ,2013-12-02,18.05,0,1.842593,1.333333,3.666667,3.666667
2711,897,6391-GBFQJ,2013-12-02,8.38,0,1.825688,0.000000,3.666667,3.666667
2712,818,8887-NCUZC,2013-12-02,49.51,6,1.863636,2.000000,2.333333,3.000000
2713,770,9149-MATVB,2013-12-02,38.50,0,1.846847,2.000000,0.000000,0.000000

In [42]:

df.query('customerID == "6708-DPYTF"')

,countryCode,customerID,InvoiceDate,InvoiceAmount,DaysLate,GlobalDaysLateLast30days,GlobalDaysLateLast3Inv,AvLateLast3,CustomerDaysLate_30days
0,391,6708-DPYTF,2012-01-03,55.37,14,14.000000,NaN,14.000000,14.000000
57,391,6708-DPYTF,2012-01-21,92.19,0,4.655172,0.000000,7.000000,7.000000
90,391,6708-DPYTF,2012-02-01,80.31,12,5.560440,4.000000,8.666667,8.666667
144,391,6708-DPYTF,2012-02-13,86.74,16,5.336842,10.333333,9.333333,9.333333
290,391,6708-DPYTF,2012-03-24,92.76,12,4.268519,12.333333,13.333333,12.000000
368,391,6708-DPYTF,2012-04-15,58.73,13,3.769912,4.333333,13.666667,12.500000
510,391,6708-DPYTF,2012-05-23,79.59,13,4.020000,17.333333,12.666667,13.000000
671,391,6708-DPYTF,2012-07-04,76.81,13,4.186275,5.000000,13.000000,13.000000
698,391,6708-DPYTF,2012-07-11,73.60,14,4.601942,4.666667,13.333333,13.500000
699,391,6708-DPYTF,2012-07-11,69.00,3,4.586538,5.666667,10.000000,13.500000
921,391,6708-DPYTF,2012-09-03,27.42,3,2.938776,5.666667,7.000000,3.000000
1171,391,6708-DPYTF,2012-11-11,94.19,4,2.678899,5.666667,2.666667,4.000000
1550,391,6708-DPYTF,2013-02-17,56.99,0,3.118812,4.666667,2.333333,0.000000
1571,391,6708-DPYTF,2013-02-24,64.64,11,2.504854,4.000000,5.000000,5.500000
1639,391,6708-DPYTF,2013-03-19,87.99,10,4.755556,11.333333,7.000000,10.500000
1644,391,6708-DPYTF,2013-03-20,81.59,9,5.054945,3.000000,10.000000,10.000000
1806,391,6708-DPYTF,2013-04-24,89.07,4,3.401786,2.666667,7.666667,4.000000
1827,391,6708-DPYTF,2013-04-29,82.04,0,3.421053,0.000000,4.333333,2.000000
1858,391,6708-DPYTF,2013-05-05,76.49,0,3.459459,0.000000,1.333333,1.333333
2342,391,6708-DPYTF,2013-09-08,64.19,2,2.504425,0.666667,0.666667,2.000000
2352,391,6708-DPYTF,2013-09-11,79.52,0,2.318182,0.000000,0.666667,1.000000
2493,391,6708-DPYTF,2013-10-03,99.22,15,2.623853,5.000000,5.666667,5.666667
2494,391,6708-DPYTF,2013-10-03,99.22,15,2.623853,5.000000,5.666667,5.666667
2495,391,6708-DPYTF,2013-10-03,105.25,1,2.585586,5.333333,5.333333,5.666667
2496,391,6708-DPYTF,2013-10-03,105.25,1,2.585586,5.333333,5.333333,5.666667
2618,391,6708-DPYTF,2013-11-07,66.92,8,1.565217,4.333333,10.666667,10.666667
2679,391,6708-DPYTF,2013-11-25,76.18,6,1.686275,4.666667,8.000000,7.000000